
import java.util.Properties

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")

if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream ->
        localProperties.load(stream)
    }
}

def supabaseUrl = localProperties.getProperty("SUPABASE_URL", "")
def supabaseKey = localProperties.getProperty("SUPABASE_KEY", "")



android {
    namespace 'com.gamerconnect.testclient'
    compileSdk 36

    defaultConfig {
        applicationId 'com.gamerconnect.testclient'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1'
        buildConfigField "String", "SUPABASE_URL", "\"${supabaseUrl}\""
        buildConfigField "String", "SUPABASE_KEY", "\"${supabaseKey}\""
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.activity:activity-compose:1.10.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.navigation:navigation-compose:2.9.5'

    def composeBom = platform('androidx.compose:compose-bom:2024.12.01')
    implementation composeBom
    androidTestImplementation composeBom

    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'

    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'

    def supabaseVersion = '3.6.0'
    def ktorVersion = '3.5.0'

    implementation platform("io.github.jan-tennert.supabase:bom:$supabaseVersion")
    implementation 'io.github.jan-tennert.supabase:auth-kt'
    implementation 'io.github.jan-tennert.supabase:postgrest-kt'
    implementation "io.ktor:ktor-client-cio:$ktorVersion"
    implementation 'io.coil-kt.coil3:coil-compose:3.4.0'
    implementation 'io.coil-kt.coil3:coil-network-ktor3:3.4.0'

    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.8.7'

    implementation 'io.github.jan-tennert.supabase:realtime-kt'
}